### ISSUE TITLE
Please document the required hardware

### ISSUE THREAD

**Issue by probonopd** [jeanthom/jtaginabox#2]
> Pick yourself a $2 ST-Link dongle (available in many chinese shops), and you will be ready to hack in minutes!

I would assume this is made to run on these:

![](https://user-images.githubusercontent.com/2480569/36065293-75ecd44a-0e90-11e8-814b-419be491dc6b.jpg)

But how about STM32F103C8T6 "Blue Pill" boards like this? (I have those lying around...) 

![](https://user-images.githubusercontent.com/2480569/36065294-78f9fcda-0e90-11e8-89b7-0a864d44158a.jpg)

**Comment by jeanthom** [comment]
Please follow this : https://github.com/jeanthom/DirtyJTAG/blob/master/docs/install-bluepill.md

DirtyJTAG is the firmware that runs on both pieces of hardware ;) The version for STLinkv2 dongles has special tweaks to allow uploading the firmware without relying on an external USB-UART board or ST-Link programmer.
