### ISSUE TITLE
jtaginabox doesn't recognize my " ST link"

### ISSUE THREAD

**Issue by long0900** [jeanthom/jtaginabox#6]
I've just installed Linux Mint, do I have to do anything else ?

**Comment by jeanthom** [comment]
Have you flashed DirtyJTAG on your ST-Link dongle, by clicking "Install DirtyJTAG on an ST-Linkv2 dongle" ?

If so, can you try running JTAG in a box as root ?

**Comment by long0900** [comment]
I tried the pre-compiled .AppImage and compiled-myself version but I didn't see any progress. I flashed my ST-link ( Bluepill actually) with stlink-tool and it made my ST-link brick for no reason ?!

**Comment by jeanthom** [comment]
"Bricking" your ST-Link is normal behavior. DirtyJTAG can both be installed on a Bluepill and ST-Link dongle (for the latter, you can do it using its USB bootloader).

What you did with stlink-tool is installing DirtyJTAG on your ST-Link dongle, not on your Bluepill board !

Here's what to do :
 * Get back to the original firmware on your ST-Link dongle with this utility : http://janjongboom.com/downloads/stsw-link007.zip
 * Follow this procedure to install DirtyJTAG on your Bluepill dongle : https://github.com/jeanthom/DirtyJTAG/blob/master/docs/install-bluepill.md

Now I'm wondering if my documentation was clear enough to prevent this kind of accident :disappointed:

**Comment by long0900** [comment]
No ! No ! My Bluepill had ST link V2 firmware on it.

**Comment by jeanthom** [comment]
Uh, ok. Please use the method I linked you in my previous message. Each DirtyJTAG platform has its own pinout and hacks (especially on ST-Link) to make it work.

**Comment by long0900** [comment]
Ok ! I will try the method for Bluepill
